language: node_js
node_js: stable

before_install
  - export TZ='Asia/Shanghai'  # 设置时区
  - npm install hexo-cli -g

# S: Build Lifecycle
install:
  - npm install

#before_script:

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "kuangzhibin"
  - git config user.email "kuangzhibin@live.com"
  - git add .
  - git commit -m "Update posts"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

# E: Build LifeCycle

branches:
  only:
    - dev
env:
  global:
    - GH_REF: https://github.com/kuangzhibin/kuangzhibin.github.io.git
